/*
 * @author Brydon Parsons
 */
package bookinventory;

/**
 *
 * @author Brydon
 */
public enum Genre{
    FANTASY, FICTION, NONFICTION, MYSTERY, SCIFI, THRILLER, HORROR, HISTORICAL,
    BIOGRAPHY, MANGA, ROMANCE, YOUNG_ADULT, WESTERN, COMPUTER_SCIENCE, DATA_SCIENCE,
    ECONOMICS, HISTORY, MATHEMATICS, PSYCHOLOGY, SCIENCE,
    SIGNAL_PROCESSING, PHILOSOPHY
}
